#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RBMotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LSciLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RSciLift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           Lclaw,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Rclaw,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor(port2) = -127; // move backward
	motor(port3) = -127;
	motor(port4) = -127;
	motor(port1) = -127;
	wait10Msec(20);
	motor(port2) = 0; // stop
	motor(port3) = 0;
	motor(port4) = 0;
	motor(port1) = 0;
	motor(port8) = 127; // raise claw
	motor(port9) = 127;
	wait10Msec(100);
	motor(port8) = -50; // raise claw
	motor(port9) = -50;
	wait10Msec(55);
	motor(port2) = 127; // move forward
	motor(port3) = 127;
	motor(port4) = 127;
	motor(port1) = 127;
	wait10Msec(200);
	motor(port2) = -80; // move back
	motor(port3) = -80;
	motor(port4) = -127;
	motor(port1) = -127;
	motor(port8) = 30;
	motor(port9) = 30;
	wait10Msec(100);
	motor(port2) = 0; // stop
	motor(port3) = 0;
	motor(port4) = 0;
	motor(port1) = 0;
	motor(port8) = 0;
	motor(port9) = 0;
	motor(port1) = -100;
	motor(port2) = -100;
	motor(port3) = 100;
	motor(port4) = 100;
	wait10Msec(55);
	motor(port2) = 0; // stop
	motor(port3) = 0;
	motor(port4) = 0;
	motor(port1) = 0;
	motor(port2) = 127; // move
	motor(port3) = 127;
	motor(port4) = 127;
	motor(port1) = 127;
	wait10Msec(15);
	motor(port2) = 0; // stop
	motor(port3) = 0;
	motor(port4) = 0;
	motor(port1) = 0;
	motor(port8) = -127; // flip cap
	motor(port7) = -127;
	wait10Msec(30);



}
